---

include:
  - project: veepee/vptech/ci-cd/markdown-lint
    ref: 1-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/semantic-release
    ref: 2-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/shellcheck
    ref: 1-latest
    file: gitlab-ci.yml

.template: &build
  stage: build
  image: docker.registry.vptech.eu/debian:bullseye
  before_script:
    - apt-get update  -qq -y
    - apt-get install -qq -y apt-transport-https ca-certificates curl debootstrap kmod gnupg-agent procps software-properties-common sudo systemd tar
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update  -qq -y
    - apt-get install -qq -y docker-ce docker-ce-cli containerd.io
    - env DOCKER_DRIVER=vfs dockerd &
  artifacts:
    expire_in: 1 day
    paths:
      - image
  tags:
    - virt-enabled
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  stage: deploy
  image: docker.registry.vptech.eu/docker:latest
  before_script:
    - docker login -u "$DOCKER_PUBLIC_REGISTRY_USERNAME" -p "$DOCKER_PUBLIC_REGISTRY_PASSWORD"
    - docker load -i image/debian-v10.0.tar
    - docker load -i image/debian-v10.0-systemd.tar
    - docker load -i image/debian-v11.0.tar
    - docker load -i image/debian-v11.0-systemd.tar
    - docker load -i image/debian-v12.0.tar
    - docker load -i image/debian-v12.0-systemd.tar
  only:
    - main
    - master
  services:
    - name: docker.registry.vptech.eu/docker:dind
      alias: docker
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - deploy
  - release

build:10:
  <<: *build
  script:
    - ./build.sh -d buster -v
    - mkdir image
    - docker save debian:buster > image/debian-v10.0.tar

build:10-systemd:
  <<: *build
  script:
    - ./build.sh -d buster -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:buster-systemd > image/debian-v10.0-systemd.tar

build:11:
  <<: *build
  script:
    - ./build.sh -d bullseye -v
    - mkdir image
    - docker save debian:bullseye > image/debian-v11.0.tar

build:11-systemd:
  <<: *build
  script:
    - ./build.sh -d bullseye -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:bullseye-systemd > image/debian-v11.0-systemd.tar

build:12:
  <<: *build
  script:
    - ./build.sh -d bookworm -v
    - mkdir image
    - docker save debian:bookworm > image/debian-v12.0.tar

build:12-systemd:
  <<: *build
  script:
    - ./build.sh -d bookworm -e "systemd" -T "systemd" -v
    - mkdir image
    - docker save debian:bookworm-systemd > image/debian-v12.0-systemd.tar

# https://hub.docker.com/u/vptech/
vptech:
  <<: *deploy
  script:
    - docker tag debian:buster           vptech/debian:10
    - docker tag debian:buster-systemd   vptech/debian:10-systemd
    - docker tag debian:buster           vptech/debian:buster
    - docker tag debian:buster-systemd   vptech/debian:buster-systemd
    - docker tag debian:bullseye         vptech/debian:11
    - docker tag debian:bullseye-systemd vptech/debian:11-systemd
    - docker tag debian:bullseye         vptech/debian:bullseye
    - docker tag debian:bullseye-systemd vptech/debian:bullseye-systemd
    - docker tag debian:bookworm         vptech/debian:12
    - docker tag debian:bookworm-systemd vptech/debian:12-systemd
    - docker tag debian:bookworm         vptech/debian:bookworm
    - docker tag debian:bookworm-systemd vptech/debian:bookworm-systemd
    - docker tag debian:buster           vptech/debian:oldstable
    - docker tag debian:bullseye         vptech/debian:stable
    - docker tag debian:bullseye         vptech/debian:latest
    - docker push --all-tags vptech/debian
# EOF
